name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/local/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Cache buildozer
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Install specific NDK version
      run: |
        yes | sdkmanager --licenses
        sdkmanager "ndk;27.3.13750724" "platforms;android-34" "build-tools;34.0.0"
        echo "ANDROID_NDK_HOME=/usr/local/android-sdk/ndk/27.3.13750724" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=/usr/local/android-sdk/ndk/27.3.13750724" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: badhabit-tracker-apk
        path: bin/*.apk
    
    - name: Display APK info
      run: |
        ls -la bin/
        echo "APK构建完成！"
        du -h bin/*.apk || echo "APK文件未找到"
